services:
  open-gateway:
    build: .
    image: open-gateway:local
    container_name: open-gateway
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=4283
    ports:
      - 4283:4283
    volumes:
      - ./config.yaml:/app/config.yaml